global using FirebaseAdmin;
global using Google.Apis.Auth.OAuth2;
global using Firebase.Auth;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Authorization;
global using Google.Cloud.Firestore;
global using Opdracht.Models;
global using System.Diagnostics;
global using Opdracht.Repositories;
global using Opdracht.Services;
global using Swashbuckle.AspNetCore;
global using Opdracht.GraphQL;
global using System.Security.Claims;
global using AuthorizeAttribute = HotChocolate.AspNetCore.Authorization.AuthorizeAttribute;
global using FluentValidation;
global using FluentValidation.AspNetCore;
global using Opdracht.Validation;
